name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 18
          - 20
          - 22

    steps:
    - name: "Checkout"
      uses: actions/checkout@v4

    - name: "Use Node.js ${{ matrix.node-version }}"
      uses: actions/setup-node@v4
      with:
        node-version: "${{ matrix.node-version }}"

    - name: "Install"
      run: yarn install

    - name: "Check for unused variables"
      run: npm run sass-sniff

    - name: "Run Jest tests"
      run: npm run test

    env:
      CI: true
