name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version:
          - "12.x"
          - "14.x"
          - "16.x"

    steps:
    - name: "Checkout"
      uses: actions/checkout@v1

    - name: "Use Node.js ${{ matrix.node-version }}"
      uses: actions/setup-node@v1
      with:
        node-version: "${{ matrix.node-version }}"

    - name: "Install"
      run: yarn install
    - name: "Check for unused variables"
      run: npm run sass-sniff
    - name: "Run Jest tests"
      run: npm run test

    env:
      CI: true
